### ISSUE TITLE
[Suggestion]: Fabric port

### ISSUE THREAD

**Issue by vico93** [Mrbysco/DistantFriends#2]
### General Info

- [ ] I would like to propose new content
- [ ] I would like to propose changes
- [X] I would like to propose another thing

### Suggestion Description

Is there any plans to a Fabric/Quilt version of the mod?

**Comment by Mrbysco** [comment]
Fabric? Sure. Quilt? Not really

**Comment by vico93** [comment]
> Fabric? Sure. Quilt? Not really

I tend to cite Quilt mostly because its compatibility with Fabric, but yeah, Fabric was what i meant at first place.

**Comment by vico93** [comment]
Any updates about this?

**Comment by Mrbysco** [comment]
Haven't found the time yet to sit down and convert the mod to a multiloader setup

**Comment by Mrbysco** [comment]
A fabric version is now available
