### ISSUE TITLE
[Suggestion]: 1.12.2 Backport

### ISSUE THREAD

**Issue by CalaMariGold** [Mrbysco/DistantFriends#3]
### General Info

- [ ] I would like to propose new content
- [ ] I would like to propose changes
- [X] I would like to propose another thing

### Suggestion Description

Hiya, I'd like to suggest a backport to 1.12.2, if you're not interested, it's no worries at all and you can close this.

If you're on the fence, I'm here to let you know that the 1.12 community is very much alive and active, and that there would be demand for your mod! There is even a [1.12 Coalition server](https://discord.gg/bj6FXsRjtp) with modders, modpack devs, and players who will gladly support your project or help along the way.

Cheers and thank you for this unique mod!

**Comment by Mrbysco** [comment]
There's no plans on backporting
