### ISSUE TITLE
[Suggestion]: Server Side Only?

### ISSUE THREAD

**Issue by acatwithagat** [Mrbysco/DistantFriends#5]
### General Info

- [ ] I would like to propose new content
- [X] I would like to propose changes
- [x] I would like to propose another thing

### Suggestion Description

Could there be a way to make a mod like this server side only? I've used the mod _Into the Fog_ before which is similar to this in some ways and it's entirely serverside except for the fact you need the resource pack which I just add into my already existing server resource pack as a requirement to join, could something like this be possible with this mod?

**Comment by Mrbysco** [comment]
No, the mod adds a new entity so the game would complain when joining and without adding the mod to the client the game won't know how to render the entity
