### ISSUE TITLE
[Bug]: DistantFriends [Error receiving packet 80]

### ISSUE THREAD

**Issue by Krimatoria** [Mrbysco/DistantFriends#6]
### General Info

- [X] I am running a modpack
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Loader version

Forge 43.3.5

### Minecraft version

Minecraft 1.19.2

### Mod version

DistantFriends-1.19.2-0.2.3.jar

### Java version

zulu-17-jre [Zulu Platform x64 Architecture]

### Issue Description

We are playing on the FearNightfall build and have added some mods to it. Of course, I have not seen such flights before. But it is on the server that throws the player out at a random moment. Sometimes quite often. 

The brother whose server sent me a log and in it at the end I saw this error immediately after I crashed. For some reason, your mod is listed in the description below.

> [20:38:58] [Netty Server IO #6/ERROR]: Error receiving packet 80
> java.util.ConcurrentModificationException: null
> 	at com.google.common.collect.LinkedHashMultimap$ValueSet$1.checkForComodification(LinkedHashMultimap.java:420) ~[guava-31.0.1-jre.jar%23121!/:?]
> 	at com.google.common.collect.LinkedHashMultimap$ValueSet$1.hasNext(LinkedHashMultimap.java:426) ~[guava-31.0.1-jre.jar%23121!/:?]
> 	at com.google.common.collect.AbstractMapBasedMultimap$WrappedCollection$WrappedIterator.hasNext(AbstractMapBasedMultimap.java:466) ~[guava-31.0.1-jre.jar%23121!/:?]
> 	at net.minecraft.nbt.NbtUtils.m_129230_(NbtUtils.java:114) ~[client-1.19.2-20220805.130853-srg.jar%23731!/:?]
> 	at com.mrbysco.distantfriends.registry.FriendSerializers$1.write(FriendSerializers.java:22) ~[DistantFriends-1.19.2-0.2.3.jar%23520!/:0.2.3]
> 	at com.mrbysco.distantfriends.registry.FriendSerializers$1.m_6856_(FriendSerializers.java:18) ~[DistantFriends-1.19.2-0.2.3.jar%23520!/:0.2.3]
> 	at net.minecraft.network.syncher.SynchedEntityData.m_135367_(SynchedEntityData.java:196) ~[client-1.19.2-20220805.130853-srg.jar%23731!/:?]
> 	at net.minecraft.network.syncher.SynchedEntityData.m_135358_(SynchedEntityData.java:140) ~[client-1.19.2-20220805.130853-srg.jar%23731!/:?]
> 	at net.minecraft.network.protocol.game.ClientboundSetEntityDataPacket.m_5779_(ClientboundSetEntityDataPacket.java:34) ~[client-1.19.2-20220805.130853-srg.jar%23731!/:?]
> 	at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:45) ~[client-1.19.2-20220805.130853-srg.jar%23731!/:?]
> 	at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:14) ~[client-1.19.2-20220805.130853-srg.jar%23731!/:?]
> 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.77.Final.jar%23114!/:4.1.77.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.77.Final.jar%23117!/:4.1.77.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-transport-4.1.77.Final.jar%23117!/:4.1.77.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-transport-4.1.77.Final.jar%23117!/:4.1.77.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-transport-4.1.77.Final.jar%23117!/:4.1.77.Final]
> 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:110) ~[netty-codec-4.1.77.Final.jar%23114!/:4.1.77.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.77.Final.jar%23117!/:4.1.77.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[netty-transport-4.1.77.Final.jar%23117!/:4.1.77.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[netty-transport-4.1.77.Final.jar%23117!/:4.1.77.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[netty-transport-4.1.77.Final.jar%23117!/:4.1.77.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808) ~[netty-transport-4.1.77.Final.jar%23117!/:4.1.77.Final]
> 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.77.Final.jar%23117!/:4.1.77.Final]
> 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-transport-4.1.77.Final.jar%23117!/:4.1.77.Final]
> 	at net.minecraft.network.Connection.m_243087_(Connection.java:209) ~[client-1.19.2-20220805.130853-srg.jar%23731!/:?]
> 	at net.minecraft.network.Connection.lambda$sendPacket$8(Connection.java:198) ~[client-1.19.2-20220805.130853-srg.jar%23731!/:?]
> 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) [netty-common-4.1.77.Final.jar%23112!/:4.1.77.Final]
> 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) [netty-common-4.1.77.Final.jar%23112!/:4.1.77.Final]
> 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) [netty-common-4.1.77.Final.jar%23112!/:4.1.77.Final]
> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503) [netty-transport-4.1.77.Final.jar%23117!/:4.1.77.Final]
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) [netty-common-4.1.77.Final.jar%23112!/:4.1.77.Final]
> 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.77.Final.jar%23112!/:4.1.77.Final]
> 	at java.lang.Thread.run(Unknown Source) [?:?]
>

**Comment by Mrbysco** [comment]
No clue what would cause that to happen

**Comment by Krimatoria** [comment]
I'm shocked myself) How could he cause such a problem on a 3-player server.
