### ISSUE TITLE
[Suggestion]: Only show distant friends that don't match the name of the player

### ISSUE THREAD

**Issue by NolanHewitt** [Mrbysco/DistantFriends#8]
### General Info

- [ ] I would like to propose new content
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

I think it would be nice if it only placed distant friends that don't have the same skin as the player they're spawning for. Would make it so they can't tell right away that it isn't actually another player.

For example, while I do have my own username in the config, whenever a distant friend is spawned near me, it should only use skins of other players, not my own.

**Comment by Mrbysco** [comment]
The skin is locked to the Distant Friend upon spawn, there's no way to make sure they never have the same skin
